[package]
name = "ttf_loader"
version = "0.1.0"
authors = ["Sergiu Paraschiv <sergiu.paraschiv@array51.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structview = "1.1.0"
